import os
import csv
from io import StringIO
from typing import Optional, List
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from app.services.di.container import get_config_service
from app.common.logging.logging_config import get_logger

TEST = get_config_service().get().app.test_mode

logger = get_logger(__name__)

class GoogleSheetsService:
    """
    Read-only service for fetching data from Google Sheets.
    Uses OAuth2 credentials from credentials.json file.
    """

    def __init__(self):
        config_service = get_config_service()
        self.scopes = config_service.get().google.scopes
        self.credentials_file = os.path.join(
            os.path.dirname(__file__),
            '..', '..', '..',
            'credentials.json'
        )
        self.token_file = os.path.join(
            os.path.dirname(__file__),
            '..', '..', '..',
            'token.json'
        )
        self._credentials = None
        self._drive_service = None
        self._sheets_service = None

    def _authenticate(self) -> None:
        """Authenticate with Google Sheets API using OAuth2 credentials."""
        if self._credentials is None:
            creds = None

            # Load token if it exists
            if os.path.exists(self.token_file):
                creds = Credentials.from_authorized_user_file(self.token_file, self.scopes)

            # Refresh or create new credentials
            if not creds or not creds.valid:
                if creds and creds.expired and creds.refresh_token:
                    creds.refresh(Request())
                else:
                    flow = InstalledAppFlow.from_client_secrets_file(
                        self.credentials_file,
                        self.scopes
                    )
                    creds = flow.run_local_server(port=0)

                # Save credentials for future use
                with open(self.token_file, 'w') as token:
                    token.write(creds.to_json())

            self._credentials = creds
            self._drive_service = build("drive", "v3", credentials=self._credentials)
            self._sheets_service = build("sheets", "v4", credentials=self._credentials)

    def fetch_spreadsheet_rows(
        self,
        spreadsheet_name: str,
        skip_initial_rows: int = 0,
        skip_final_rows: int = 0
    ) -> dict[str, List[List[str]]]:
        """
            Fetches all data from a Google Spreadsheet by name and returns a dictionary
            with sheet names as keys and lists of rows for each sheet. Each row is represented as a list of strings.

            Args:
                spreadsheet_name: The exact name of the Google Spreadsheet to search for.
                skip_initial_rows: Number of rows to skip from the beginning of each sheet (default: 0).
                skip_final_rows: Number of rows to skip from the end of each sheet (default: 0).

            Returns:
                dict[str, List[List[str]]]: Dictionary mapping sheet names to their rows as lists of strings.
                            Returns empty dict if spreadsheet not found.

            Raises:
                Exception: If there's an error accessing the Google Sheets API.
            """
        # Ensure authentication
        self._authenticate()

        try:
            # Step 1: Search for the spreadsheet by name in Drive
            query = f"name = '{spreadsheet_name}' and mimeType='application/vnd.google-apps.spreadsheet'"
            results = self._drive_service.files().list(
                q=query,
                fields="files(id, name)"
            ).execute()
            files = results.get("files", [])

            if not files:
                return {}  # Return empty dict if not found

            # Step 2: Get spreadsheet metadata
            spreadsheet_id = files[0]["id"]
            spreadsheet = self._sheets_service.spreadsheets().get(
                spreadsheetId=spreadsheet_id
            ).execute()
            sheet_list = spreadsheet.get("sheets", [])

            sheets_dict = {}

            # Step 3: Loop through each sheet and load its contents
            for sheet in sheet_list:
                sheet_title = sheet["properties"]["title"]
                range_name = f"{sheet_title}"

                result = self._sheets_service.spreadsheets().values().get(
                    spreadsheetId=spreadsheet_id,
                    range=range_name
                ).execute()

                rows = result.get("values", [])

                if not rows:
                    # Add empty CSV for empty sheets
                    sheets_dict[sheet_title] = None
                    continue

                # Apply row truncation
                total_rows = len(rows)
                start_index = skip_initial_rows
                end_index = total_rows - skip_final_rows

                # Ensure valid indices
                if start_index < 0:
                    start_index = 0
                if end_index > total_rows:
                    end_index = total_rows
                if start_index >= end_index:
                    # All rows are skipped
                    sheets_dict[sheet_title] = None
                    continue

                sheets_dict[sheet_title] = rows[start_index:end_index]
            
            logger.info(f"Fetched spreadsheet '{spreadsheet_name}' successfully.")

            return sheets_dict

        except HttpError as e:
            logger.error(f"Error fetching spreadsheet '{spreadsheet_name}': {e}")
            raise Exception(f"Error fetching spreadsheet '{spreadsheet_name}': {e}")

class MockGoogleSheetsService(GoogleSheetsService):
    """
    Mock version of GoogleSheetsService for testing purposes.
    Overrides methods to return predefined data instead of making actual API calls.
    """

    def fetch_spreadsheet_rows(
        self,
        spreadsheet_name: str,
        skip_initial_rows: int = 0,
        skip_final_rows: int = 0
    ) -> dict[str, List[List[str]]]:
        # Return mock data for testing
        mock_data = {'Asset Allocation': [['',
                       '',
                       'Asset Classes',
                       'Subclasse',
                       'Valor Atual',
                       '% Atual',
                       '% Meta',
                       '',
                       'Valores $',
                       'Diferença'],
                      ['',
                       '',
                       'RENDA FIXA',
                       '',
                       'R$243.301',
                       '54,79%',
                       '60,00%',
                       '',
                       'R$266.451',
                       '-R$23.150'],
                      ['',
                       '',
                       '',
                       'Curto Prazo',
                       'R$42.374',
                       '9,54%',
                       '12,00%',
                       '',
                       'R$53.290',
                       '-R$10.916'],
                      ['',
                       '',
                       '',
                       'Médio Prazo',
                       'R$48.580',
                       '10,94%',
                       '29,00%',
                       '',
                       'R$128.785',
                       '-R$80.205'],
                      ['',
                       '',
                       '',
                       'Longo Prazo',
                       'R$108.063',
                       '24,33%',
                       '9,00%',
                       '',
                       'R$39.968',
                       'R$68.096'],
                      ['',
                       '',
                       '',
                       'Short Term',
                       'R$10.526',
                       '2,37%',
                       '3,00%',
                       '',
                       'R$13.323',
                       '-R$2.796'],
                      ['',
                       '',
                       '',
                       'Intermediate',
                       'R$17.591',
                       '3,96%',
                       '5,00%',
                       '',
                       'R$22.204',
                       '-R$4.614'],
                      ['',
                       '',
                       '',
                       'Long Term',
                       'R$16.167',
                       '3,64%',
                       '2,00%',
                       '',
                       'R$8.882',
                       'R$7.286'],
                      ['',
                       '',
                       'STOCKS',
                       '',
                       'R$94.085',
                       '21,19%',
                       '20,00%',
                       '',
                       'R$88.817',
                       'R$5.268',
                       '',
                       'Avenue',
                       'R$170.081'],
                      ['',
                       '',
                       '',
                       'US Stocks',
                       'R$28.306',
                       '6,37%',
                       '4,00%',
                       '',
                       'R$17.763',
                       'R$10.543',
                       '',
                       'XP Investimentos',
                       'R$274.004'],
                      ['',
                       '',
                       '',
                       'World Stocks',
                       'R$27.535',
                       '6,20%',
                       '3,00%',
                       '',
                       'R$13.323',
                       'R$14.213',
                       '',
                       'Banco Inter',
                       'R$0'],
                      ['',
                       '',
                       '',
                       'Brasil Stocks',
                       'R$38.243',
                       '8,61%',
                       '8,00%',
                       '',
                       'R$35.527',
                       'R$2.716',
                       '',
                       'TOTAL',
                       'R$444.085'],
                      ['',
                       '',
                       '',
                       'Fundo de Investimento',
                       'R$0',
                       '0,00%',
                       '5,00%',
                       '',
                       'R$22.204',
                       '-R$22.204'],
                      ['',
                       '',
                       'COMMODITIES',
                       '',
                       'R$35.427',
                       '7,98%',
                       '4,00%',
                       '',
                       'R$17.763',
                       'R$17.663'],
                      ['',
                       '',
                       '',
                       'Ouro',
                       'R$35.427',
                       '7,98%',
                       '4,00%',
                       '',
                       'R$17.763',
                       'R$17.663'],
                      ['',
                       '',
                       '',
                       'Prata',
                       'R$0',
                       '0,00%',
                       '0,00%',
                       '',
                       'R$0',
                       'R$0'],
                      ['',
                       '',
                       'CRIPTOCURRENCY',
                       '',
                       'R$19.200',
                       '4,32%',
                       '5,00%',
                       '',
                       'R$22.204',
                       '-R$3.004'],
                      ['',
                       '',
                       '',
                       'Bitcoin',
                       'R$14.400',
                       '3,24%',
                       '4,00%',
                       '',
                       'R$17.763',
                       '-R$3.363'],
                      ['',
                       '',
                       '',
                       'Altcoin',
                       'R$4.800',
                       '1,08%',
                       '1,00%',
                       '',
                       'R$4.441',
                       'R$359'],
                      ['',
                       '',
                       'REAL ESTATE',
                       '',
                       'R$52.072',
                       '11,73%',
                       '11,00%',
                       '',
                       'R$48.849',
                       'R$3.223'],
                      ['',
                       '',
                       '',
                       'REITs',
                       'R$34.528',
                       '7,78%',
                       '7,00%',
                       '',
                       'R$31.086',
                       'R$3.442'],
                      ['',
                       '',
                       '',
                       'Fundos Imobiliários',
                       'R$17.544',
                       '3,95%',
                       '4,00%',
                       '',
                       'R$17.763',
                       '-R$219'],
                      ['', '', 'Total', '', 'R$444.085', '100,00%', '100,00%'],
                      [],
                      ['',
                       '',
                       'Exposição em Moeda Forte',
                       '',
                       'R$161.746',
                       '36,42%',
                       '32,00%'],
                      [],
                      ['', 'Renda Fixa Brasil'],
                      ['',
                       '',
                       'Nome do Título',
                       'Código/Taxa',
                       'Tipo',
                       'Quantidade',
                       ' Preço Médio',
                       'Preço Atual',
                       'Valor Atual',
                       'Retorno',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'Caixa',
                       '',
                       'CDI',
                       '',
                       '',
                       '',
                       'R$0,00',
                       '',
                       '0,00%',
                       'XP'],
                      ['',
                       '',
                       'Porto Seguro FIRF Referenciado DI CP',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$42.014,00',
                       '',
                       '21,11%',
                       'XP'],
                      ['',
                       '',
                       'Trend Investback FIRF ',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$360,00',
                       '',
                       '0,18%',
                       'XP'],
                      ['',
                       'Total Curto Prazo',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$42.374,00'],
                      ['',
                       '',
                       'CDB PINE - ABR/2027',
                       '',
                       'Pré 15% a.a.',
                       '',
                       'R$21.000,00',
                       '',
                       'R$22.001,00',
                       'R$1.001,00',
                       '11,05%',
                       'XP'],
                      ['',
                       '',
                       'CDB DM FINANCEIRA - ABR/2027',
                       '',
                       '123% CDI',
                       '',
                       'R$22.000,00',
                       '',
                       'R$26.579,00',
                       'R$4.579,00',
                       '13,36%',
                       'XP'],
                      ['',
                       'Total Médio Prazo',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$48.580,00'],
                      ['',
                       '',
                       'DEB AEGEA - JAN/2031',
                       '',
                       'Pré 15.86% a.a.',
                       '',
                       'R$26.228,85',
                       '',
                       'R$25.630,00',
                       '-R$598,85',
                       '12,88%',
                       'XP'],
                      ['',
                       '',
                       'CDB NBC Bank - MAIO/2032',
                       '',
                       '14.97% a.a.',
                       '',
                       'R$10.000,00',
                       '',
                       'R$10.395,00',
                       'R$395,00',
                       '5,22%',
                       'XP'],
                      ['',
                       '',
                       'PHRONESIS TEVA IPCA DYNAMIC SELECTION YIELD FUNDO DE '
                       'INDICE',
                       'PHIP11',
                       '',
                       '321,00',
                       'R$107,81',
                       'R$107,96',
                       'R$34.655,16',
                       'R$48,15',
                       '17,41%',
                       'XP'],
                      ['',
                       '',
                       'NTN-b1',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$37.383,00',
                       '',
                       '18,78%',
                       'XP'],
                      ['',
                       'Total Longo Prazo',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$108.063,16'],
                      ['Total Renda Fixa BR',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$199.017,16'],
                      [],
                      ['', 'Renda Fixa EUA'],
                      ['',
                       '',
                       'Nome do Título',
                       'Código/Taxa',
                       'Tipo',
                       'Quantidade',
                       ' Preço Médio',
                       'Preço Atual',
                       'Valor Atual',
                       'Retorno',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'iShares Treasury Floating Rate Bond ETF',
                       'TFLO',
                       'Short Term',
                       '39,53',
                       'R$50,60',
                       'R$50,49',
                       '$1.995,65',
                       '-R$4,35',
                       '23,77%',
                       'AVENUE'],
                      ['',
                       'Total Short Term/ Pós Fixado',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '$1.995,65'],
                      ['',
                       '',
                       'iShares 5-10 Yr Investment Grade Corporate Bd ETF',
                       'IGIB',
                       'Short Term',
                       '61,6784',
                       '$52,69',
                       '$54,07',
                       '$3.334,95',
                       '$85,12',
                       '',
                       'AVENUE'],
                      ['',
                       'Total Intermediate',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '$3.334,95'],
                      ['',
                       '',
                       'iShares 20+ Year Treasury Bond ETF',
                       'TLT',
                       'Long Term',
                       '34,07',
                       'R$86,50',
                       'R$89,96',
                       '$3.065,14',
                       'R$117,89',
                       '36,51%',
                       'AVENUE'],
                      ['',
                       'Total Long Term',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '$3.065,14'],
                      ['Total Renda Fixa EUA',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '$8.395,74'],
                      [],
                      ['', 'Multimercado'],
                      ['',
                       'Nome do Fundo',
                       '',
                       'Ticker',
                       'Subsetor',
                       'Qtd',
                       ' Preço Médio',
                       'Preço Atual',
                       'Valor Atual',
                       'Resultado',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'Kinea Prev XP Seg IPCA Dinâmico',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '#DIV/0!',
                       'XP'],
                      ['',
                       'Total Fundos',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$0,00',
                       '',
                       '#DIV/0!'],
                      [],
                      ['', 'Commodities'],
                      ['',
                       'Nome do Fundo',
                       '',
                       'Ticker',
                       'Subsetor',
                       'Qtd',
                       ' Preço Médio',
                       'Preço Atual',
                       ' Valor Investido',
                       'Valor Atual',
                       'Resultado',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'VanEck Gold Miners ETF',
                       'GDX',
                       'Ouro/Mineradora',
                       '87,55632',
                       '$51,97',
                       'R$76,71',
                       '$4.550,30',
                       '$6.716,45',
                       '$2.166,14',
                       '',
                       'AVENUE'],
                      ['',
                       'Total Commodities',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '$6.716,45'],
                      [],
                      ['', 'Stocks US'],
                      ['',
                       'Nome da Empresa',
                       '',
                       'Ticker',
                       'Subsetor',
                       'Qtd',
                       ' Preço Médio',
                       'Preço Atual',
                       ' Valor Investido',
                       'Valor Atual',
                       'Resultado',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'Avantis US Small Cap Value ETF',
                       'AVUV',
                       '',
                       '54,21321',
                       '$93,05',
                       '$98,99',
                       '$5.044,54',
                       '$5.366,57',
                       '$322,03',
                       '',
                       'AVENUE'],
                      ['',
                       'Total Stocks / BDRs',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '$5.366,57'],
                      [],
                      ['', 'World Stocks'],
                      ['',
                       'Nome da Empresa',
                       '',
                       'Ticker',
                       'Subsetor',
                       'Qtd',
                       ' Preço Médio',
                       'Preço Atual',
                       ' Valor Investido',
                       'Valor Atual',
                       'Resultado',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'Avantis Emerging Markets Equity ETF',
                       'AVEM',
                       '',
                       '66,83333',
                       '$67,93',
                       '$78,11',
                       '$4.539,99',
                       '$5.220,35',
                       '$680,36',
                       '',
                       'AVENUE'],
                      ['',
                       'Total Stocks / BDRs',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$5.220,35'],
                      [],
                      ['', 'Acões BR'],
                      ['',
                       'Nome da Empresa',
                       '',
                       'Ticker',
                       'Subsetor',
                       'Qtd',
                       ' Preço Médio',
                       'Preço Atual',
                       ' Valor Investido',
                       'Valor Atual',
                       'Resultado',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'IT Now IFNC Fundo de Índice',
                       'FIND11',
                       '',
                       '79',
                       'R$144,95',
                       'R$144,09',
                       'R$11.451,05',
                       'R$11.383,11',
                       '-R$67,94',
                       '29,77%',
                       'XP'],
                      ['',
                       '',
                       'NU Ibov Smart Low Volatility B3 Fundo de Indice',
                       'LVOL11',
                       '',
                       '218',
                       'R$101,29',
                       'R$123,21',
                       'R$22.081,22',
                       'R$26.859,78',
                       'R$4.778,56',
                       '70,23%',
                       'XP'],
                      ['',
                       'Total Ações',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$38.242,89',
                       'R$4.710,62'],
                      [],
                      ['', 'REITs'],
                      ['',
                       'Nome do REIT',
                       '',
                       'Ticker',
                       'Subsetor',
                       'Qtd',
                       ' Cota Aquisição',
                       'Cota Atual',
                       ' Valor Investido',
                       'Valor Atual',
                       'Resultado',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'Real Estate Select Sector SPDR Fund',
                       'XLRE',
                       'ETF Equity',
                       '156,98181',
                       '$41,30',
                       '$41,70',
                       '$6.483,35',
                       '$6.546,14',
                       '$62,79',
                       '100,00%',
                       'Avenue'],
                      ['',
                       'Total REITs',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '$6.483,35',
                       '$6.546,14'],
                      [],
                      ['', 'FUNDOS IMOBILIÁRIOS'],
                      ['',
                       'Nome do FII',
                       '',
                       'Ticker',
                       'Subsetor',
                       'Qtd',
                       ' Cota Aquisição',
                       'Cota Atual',
                       ' Valor Investido',
                       'Valor Atual',
                       'Resultado',
                       '% Carteira',
                       'ONDE?'],
                      ['',
                       '',
                       'Inter Teva Indice de Tijolo FI Imobiliario',
                       'ITIT11',
                       '',
                       '258',
                       'R$65,76',
                       'R$68,00',
                       'R$16.966,08',
                       'R$17.544,00',
                       'R$577,92',
                       '100,00%',
                       'XP'],
                      ['',
                       'Total FIIs',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$16.966,08',
                       'R$17.544,00',
                       'R$577,92',
                       '100,00%'],
                      [],
                      ['', 'Criptos'],
                      ['',
                       'Nome do Fundo',
                       '',
                       'TICKER',
                       'Quantidade',
                       ' $ Preço Médio',
                       ' $ Preço',
                       ' Valor Investido',
                       'Valor Atual',
                       'Resultado',
                       '% Retorno',
                       '% Carteira',
                       '% Meta',
                       'ONDE?'],
                      ['',
                       '',
                       'Hashdex Nasdaq Crypto Index Fundo de Indice',
                       'HASH11',
                       '256',
                       'R$70,44',
                       'R$75,00',
                       'R$18.032,64',
                       'R$19.200,00',
                       'R$1.167,36',
                       'R$0,06',
                       '100,00%',
                       '0,55',
                       'XP'],
                      ['',
                       '% Carteira',
                       '% Meta',
                       'ONDE?'],
                      ['',
                       '',
                       'Hashdex Nasdaq Crypto Index Fundo de Indice',
                       'HASH11',
                       '256',
                       'R$70,44',
                       'R$75,00',
                       'R$18.032,64',
                       'R$19.200,00',
                       'R$1.167,36',
                       'R$0,06',
                       '100,00%',
                       '0,55',
                       'XP'],
                      ['',
                       'Hashdex Nasdaq Crypto Index Fundo de Indice',
                       'HASH11',
                       '256',
                       'R$70,44',
                       'R$75,00',
                       'R$18.032,64',
                       'R$19.200,00',
                       'R$1.167,36',
                       'R$0,06',
                       '100,00%',
                       '0,55',
                       'XP'],
                      ['',
                       'R$70,44',
                       'R$75,00',
                       'R$18.032,64',
                       'R$19.200,00',
                       'R$1.167,36',
                       'R$0,06',
                       '100,00%',
                       '0,55',
                       'XP'],
                      ['',
                       'R$18.032,64',
                       'R$19.200,00',
                       'R$1.167,36',
                       'R$0,06',
                       '100,00%',
                       '0,55',
                       'XP'],
                      ['',
                       'R$1.167,36',
                       'R$0,06',
                       '100,00%',
                       '0,55',
                       'XP'],
                      ['',
                       'R$0,06',
                       '100,00%',
                       '0,55',
                       'XP'],
                      ['',
                       '0,55',
                       'XP'],
                      ['',
                      ['',
                       'Total Cripto',
                       '',
                       '',
                       '',
                       '',
                       '',
                       '',
                       'R$19.200,00']]]}
        
        logger.warning('Mock data returned from Google Sheets Service')
        return mock_data

if TEST:
    GoogleSheetsService = MockGoogleSheetsService